### ISSUE TITLE
Coursework feedback

### ISSUE THREAD

**Issue by NYBACHOK** [sp-sofi/json_rust_parser#1]
Student: напиши своє ім'я

Для прохідного: 
✔️ ! CLI: 
✔️ ! Brief Description:
✔️ ! Project Name:
✔️ ! Grammar Rules:
✔️ ! Unit Tests:
✔️ ! Core Files:

Для мааксимального:
❌ File System:   Read input from file and write output to a file specified by user.
✔️ Test Coverage:
❌ Error Handling: у тестах все окай
✔️ cargo fmt:
❌ cargo clippy: після оновлень
❌ makefile: makefile should include commands to launch the program and to run tests, format and clipply before committing as well other useful commands.
❌ Completeness:
❌ Including a diagram or grammar in the Readme.md: скопіюй правила з `grammar.pest` у `Readme.md` 
❌ Documentation:
❌ Publishing: опублійк на creates.io й додай посилання у  `Readme.md` 

Курсова може бути зарахована ✔️
Бал: 10/25

**Comment by sp-sofi** [comment]
Student: Прочна Софья 
Можу заливати проєкт на дістеду?)
